CREATE_USER_PATH = "/api/v1/users/"
URL_SERVICE = "https://5f499e53-334c-447c-8d40-1f1b32368e4e.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"